[package]
name = "retry-cli"
version = "0.2.2"
edition = "2021"

[dependencies]
clap = { version = "3.1", features = ["derive"] }
humantime = "2.1"
tokio = { version = "1", features = ["macros", "process", "rt-multi-thread", "signal"] }
